#!/bin/sh

home=$HOME
cwd=$(pwd)

ln -sf $cwd/_tmux.conf $home/.tmux.conf
git clone https://github.com/tmux-plugins/tpm $home/.tmux/plugins/tpm

echo 'Press C-b I to install plugins in tmux.'
sleep 2
tmux
exit 0
